sudo: false
language: node_js
node_js:
  - '6.2'
env:
  global:
    - GH_REF: github.com/longseespace/longseespace.github.io.git
    - secure: >-
        xnM50UhtOW0KIg9UdfhOGWhvInS7BHLlXGbQcI93d4yQMWzWzaCmyoZcD8ouwdIR7zWdJzFqwC4ep666IezAAOgn7VjKQxkEgGL/bM8BrmetXKFWiH5a1gvf0VuHs39EeQd/fJhUWD0fYDQvM41kqyUN/E9QJ+U3rxHCt8kFHWlYQS6uhsIly+pF+4g9cJbqz7RIuIU3Oxd/+bIAtf9zMnJfMpLmUdonMuqxM5DyEZo8bBE1eiMdUq+fjLJWAT9Yo0a+foMOy/7Bh4sh5tWoneMYq//eyrIr/PTMrDi6mJU+TAaO+K8MPck8eO+fRpmW+JTk/HiSujBTICxHW5MuYcNU6YJ6mnenplQpMHFwQFUH45yrAxSOmkmM7V9KVutGJLqqvXVU1IIS11uWsx6R/0jCmKXigFTwggLIsWIYoz4ObAFOfQ46TjoI8gtinfo9Oo1PRIYWukWf//MByvGacEklByRt7/mYRaJ1iTAPl52Bw98+GkMHchu+qU1Thj5k7Z57/Cz1exX9HRNCzKy5x11D41DdYfiieSopH02yDCmcWDe6N7UGSm8FwX6qbOiKOLbnPJw3oeae3BAzzn+lGEA/hDhWsYtz4Vziqd58At+7XJyv5/1rfRleSWFE75+whX94V/HSsloOEF3uuVwiyhjzJ+yTm8MnEYaCjwbVZlg=
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g hexo-cli
script:
  - hexo generate
after_success:
  - chmod +x ./deploy.sh && ./deploy.sh
